---
resource_id: "39e3afb1-4acb-435f-83d6-f73016bb839c"
title: "Project 0: Introduction"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 1
draft: false
# search related keywords
keywords: [""]
---


<!-- section_id: "444bece1-74f2-4958-925e-679b523d10e4" -->
### Walkthrough

```{=html}
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1157612/sp/115761200/embedIframeJs/uiconf_id/41338032/partner_id/1157612?iframeembed=true&playerId=kaltura_player&entry_id=1_u380lmyb&flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_599ex7zw" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="W01 - Project 0 Walkthrough"></iframe>
```


<!-- section_id: "ee653ea4-6e41-4574-96a8-ffc8881c274a" -->
### Background

::: {.callout-note collapse="false"}

We will complete six projects during the semester that each take about two weeks (four days of class).  On average, a student will spend 2 hours outside of class per hour in class to complete the assigned readings, submit any Canvas items, and complete the project **(for a total of 8 hours per project)**. The instruction for each project will be structured into sections as written on this page. 

This first Background section provides context for the project. Make sure you read the background carefully to see the big picture needs and purpose of the project.
:::

Python and VS Code are tools commonly used in the field of data science. During our first two days of class we will get VS Code prepped for data science programming. Completing Project 0 will set you up for success the rest of the semester.


<!-- section_id: "bf617b39-70df-4368-80c9-640d4307f096" -->
### Data

::: {.callout-note collapse="false"}
Every data science project should start with data, and our class projects are no different. Each project will have __'Download'__ and __'Information'__ links like the ones below.
:::

__URL:__ [penguins data](https://aeturrell.github.io/python4DS/data-visualise.html#the-penguins-data-frame)   

```python
penguins = load_penguins()
penguins
```

<!-- section_id: "0f9efc9b-516e-4271-8486-e7c6b6e18fed" -->
### Readings

::: {.callout-note collapse="false"}
The Readings section will contain links to reading assignments that are required for each project, as well as optional references. Remember that you are reading this material to build skills. Take the time to comprehend the readings and the skills contained within.  

We recommend reading through the assigned material once for a general understanding **before the first day of each project**.  You will reread and reference the material multiple times as you complete the project.
:::

The readings listed below are required for the first two days of class.

- [Course Setup](../setup.qmd) (Do)
- [Learn about our Book Python for Data Science](../Course%20Materials/python.qmd) (Skim)
- [PY4DS: First Steps](https://aeturrell.github.io/python4DS/introduction.html) (Skim)
- [PY4DS: CH1 Whole Game](https://aeturrell.github.io/python4DS/whole-game.html) (Skim)
- [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) (Read)
- [P4DS: CH30 Markdown](https://aeturrell.github.io/python4DS/markdown.html) (Read)
- [P4DS: CH31 Quarto](https://aeturrell.github.io/python4DS/quarto.html) (Skim)
- [Quarto Instructional Template for DS](../Templates/ds250_project_template.qmd) (Read)


#### Optional References
- [Learn about VS Code](../Course%20Materials/vs_code.qmd)
- [VS Code user interface](https://code.visualstudio.com/docs/getstarted/userinterface) 
- [Reading Technical Documentation](https://byui-cse.github.io/cse450-course/course/reading-technical-documentation.html)


<!-- section_id: "3a613a93-e49d-4e4c-afc8-992f23a2bcdc" -->
### Questions and Tasks

::: {.callout-note collapse="false"}
This section lists the questions and tasks that need to be completed for the project. Your work on the project must be compiled into a report, rendered to a HTML file and uploaded in Canvas.
:::

1. __Download this [Project0 Template](../Templates/P0_template.qmd) template as has working code for the Penguine data set. You need to finish the project by updating its markdown so that it is a report by completing the following tasks:__
    1. __Include the tables created from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) used to create the above chart__  
    2. __Recreate the example charts from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) of the textbook.__  
    3. __Follow the instructions in the submission section below to submit your work__


<!-- section_id: "db347f69-ceda-440a-b9cd-eb563c95632c" -->
### Submission:
::: {.callout-note collapse="false"}
When you have completed the report, you will need to follow this process to submit your work:

1. Have the `P0_template` open in VS Code and nothing else
1. Click `Preview Button` in VS Code in the top right of the screen
    a. This will render the project but also entire course work portfolio into `HTML` files for review
    b. Confirm everything displas as you would like it to
    c. How you see it will be how it is viewed for grading
    d. If there is an error in any cell of the quarto files, the rendering will stop and you will need to fix the error before rendering again (if you get stuck post your error in Slack)
1. Once the report is confirmed close the preview and open a VS Code `Terminal`
    a. click `Terminal` in the top menu bar and then `New Terminal`
1. Type the following in the terminal `quarto render `
    a. Then drag and drop `P0_template.qmd` into the terminal this will add the file path to the terminal command
    a. Press Enter
1. This will render the project into a `HTML` file in the same location as the `.qmd` file
1. To locate the file in VS Code
    a. Right click on the file in the file explorer and select `Reveal in File Explorer`(Win) or `Reveal in Finder`(Mac)
1. Upload `HTML` file into Canvas
:::


<!-- section_id: "3446dd71-ffe0-41a1-a818-1dd74b4aed8b" -->
### Deliverables:

::: {.callout-note collapse="false"}
Deliverables are “the quantifiable goods or services that must be provided upon the completion of a project”. In this class the deliverable for each project is a GitHub published report created using Quarto files. This final section will be the same for each project. 
:::

_Use this [P0_template](../Templates/P0_template.qmd) to submit your Client Report._
 
1. _The template should include answers to the questions | tasks. Each should include a written description of your results, code cells with comments, charts and/or tables._  
1. _Write short __summary of work must__ be submitted in the comments in Canvas wwhen you submit the URL. Rate your own work on a scale of 1-5 (See the Rubric for Details) Include a short description of why you rated your work the way you did._

::: {.callout-note collapse="false"}
_Your report should be written in quarto markdown files and rendered to an HTML File. Upload the HTML file in Canvas. (Do not submit the `.qmd` file)_  
:::


<!-- section_id: "bbc71909-d908-4119-92b4-1cfa37379f7c" -->
### Feedback:
::: {.callout-note collapse="false"}
If you submit before the due date, you will recieve feedback and/or coaching notes. You will need to address the feedback, re-render and resubmit the project.
:::


<!-- section_id: "d1a89940-2aee-4bc7-bb2b-c33487eff947" -->
### Resubmission:
::: {.callout-note collapse="false"}
_If you submit before the due date_, you will have __one__ opportunity to resubmit the project after you have received feedback. The window for the resubmission will be open through the __Wednesday__ following the due date of the project.
:::