---
resource_id: "5e912a85-5652-4945-a4f8-b836797c77c4"
title: "Project 1 Workbook"
subtitle: "Course DS 250"
author: "Brother Clark"
uses: quarto-dev/quarto-actions/publish@v2
with:
  target: gh-pages
  to: html # If set, it will be equivalent to `quarto render --to html`
  path: source-folder # By default, the current working dir is used i.e `quarto render .`
#jupyter: python3
format: #hugo-md
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-copy: true
    code-fold: true
    code-line-numbers: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-tools:
        source: false
        toggle: true
        caption: See code
execute:
    warning: false
    
---


# Project 1 WorkBook


<!-- section_id: "b5115c6b-26a4-4d35-bb6c-7b35bdb87a7d" -->
## Tutoring Lab Info
The [data science lab](https://byuidatascience.github.io/lab/) is a resource you can use in person, online, and in Slack.

---

# Introduction to Markdown Language

---

::: {.callout-note collapse="true"}
<!-- section_id: "6429601d-0af0-4bda-b505-a96239124e89" -->
## Expand To See Links to Chapter in the book `Python4DS`
- [Chapter on Mardown: Text Block Syntax](https://aeturrell.github.io/python4DS/markdown.html)
- [Additional Resource: Basic Syntax Markdown Guide](https://www.markdownguide.org/basic-syntax/)
:::
````
Surround ```chunks of code``` with ``` or a single line of `code` with `
Follow the first set of ``` with the words `python`

```python
# setup
import pandas as pd
import numpy as np
import plotly.express as px
```
````
:::{.callout-tip collapse="true" title="Expand To See The Results"}
<br>

```python
# setup

import pandas as pd
import numpy as np
import plotly.express as px
```

:::

<!-- section_id: "36b8f37b-b6cf-4571-acf8-5d7cc15d82b7" -->
## Text Basics
<!-- section_id: "27709f37-0cc2-4185-873e-c18e5f75d32e" -->
### Horizontal Lines

Add horizontal lines with either three `---`, `***`, or `___`
But you also need blank lines above and below them

:::{.callout-tip collapse="true" title="Expand To See The Results"}
<br>
---

:::

<!-- section_id: "401f1ac7-53f6-481f-8595-f3499721a224" -->
### Headers
````
# Level 1 Header
<!-- section_id: "5882ab11-0c5f-47e5-aeb9-051f6da4125f" -->
## Level 2 Header
<!-- section_id: "6dd9b97c-5236-4149-bb93-ee4dd405eded" -->
### Level 3 Header
#### Level 4 Header
##### Level 5 Header
###### Level 6 Header
````
Note: only top 3 Levels of Headers will automatically generate a table of contents.<br> Also Level 2 will automatically add a line underneath it. 

::: {.callout-tip collapse="true"}
<!-- section_id: "30448038-cd7d-4cde-b354-dd94dd9a119c" -->
## Expand To See The Results
# Level 1 Header
<!-- section_id: "5fc49e8b-6819-4e1c-a78c-0fee5a1d79b6" -->
## Level 2 Header
<!-- section_id: "49321bab-7a89-4ff1-9c01-2cc375eea4fd" -->
### Level 3 Header
#### Level 4 Header
##### Level 5 Header
###### Level 6 Header
:::

<!-- section_id: "791de8e3-2c2b-4541-8f39-9f68ef162e74" -->
### Italics and Bold
````
_italics_ use one `_`
you can also use _mid_ sentence

__bold__ use two `__`
you can also use __mid__ sentence
````
::: {.callout-tip collapse="true"}
<!-- section_id: "2efab506-5014-4d42-b7f6-ac62eceef1c0" -->
## Expand To See The Results
_italics_ use one `_`
you can also use _mid_ sentence

__bold__ use two `__`
you can also use __mid__ sentence
:::

<!-- section_id: "d4e38798-cd20-4fd9-ab5e-74cc42317c4b" -->
### Bullet Items
````
- Bulleted items
  - Indented bulleted items
  - You can have as many as you want
    - Really as many as you want
      - I knew you wanted one more
````
::: {.callout-tip collapse="true"}
<!-- section_id: "b818eb6e-3cba-4291-bcb3-d086a49d6928" -->
## Expand To See The Results
- Bulleted items
  - Indented bulleted items
  - You can have as many as you want
    - Really as many as you want
      - I knew you wanted one more bullet
:::
<!-- section_id: "80840d2a-ab05-4eb6-883d-507626529eb8" -->
### Numbered Items
````
1. Numbered items
1. Numbered items continued
1. Dont worry these will iterate
1. Keep using 1. each time
````
::: {.callout-tip collapse="true"}
<!-- section_id: "6ec4526f-1479-4715-a14d-7b69e9580618" -->
## Expand To See The Results
1. Numbered items
1. Numbered items continued
1. Dont worry these will iterate
1. Keep using 1. each time
:::

---

# Intro to Pandas

---

<!-- section_id: "c74fe551-fd98-4d1f-89ee-a27df39a957c" -->
## Pandas DataFrame (`df`)

::: {.callout-note collapse="true"}
<!-- section_id: "08d56fc8-2753-4b0a-a02d-b3b99a041725" -->
## Expand To See Links to Chapter in the book `Python4DS`
- [Chapter on Pandas: DataFrames](https://aeturrell.github.io/python4DS/data-transform.html)
:::

What is a pandas dataFrame? We can read the [official documentation](https://pandas.pydf.org/pandas-docs/stable/user_guide/dsintro.html#dataframe). I also like the video in [this tutorial](https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python).

Use the Import Packages and Load df for the Code that follows.

<!-- section_id: "33bc4937-73f7-4105-bd6a-a27e3a8d4477" -->
## Import Packages
````{}
import `library` as `alias`
````

```{.python filename="Import Libraries"}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px

from IPython.display import Markdown
from IPython.display import display
```

<!-- section_id: "58d2463f-6598-4f5e-9336-d8e1a0c98709" -->
## Load Data
```{}
df = pd.read_csv(`url` or `file_path`)
```

```{.python filename="Load Data"}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
url = "https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv"
df = pd.read_csv(url)
```

Data Frames come with attributes and built-in functions that can help us get a feel for our df.

Run the code below one at a time (or use other functions of your choice) to explore the `names` df. What do you learn?

```{.python filename=".columns"}
df.columns
```
```{.python filename=".shape"}
df.shape
```
```{.python filename=".size"}
df.size
```
```{.python filename=".head()"}
df.head()
```
```{.python filename=".describe()"}
df.describe()
```
<!---- https://towardsdatascience.com/wrangling-data-with-pandas-27ef828aff01 ----->

<!-- section_id: "7081eaa0-a636-405a-b270-b1841cd4fcba" -->
## Pandas Data Transformation

::: {.callout-note collapse="true"}
<!-- section_id: "f365aa82-c902-4960-9ea0-ff830cd4c969" -->
## Expand To See Links to Chapter in the book `Python4DS`
- [Chapters Transformation: 15-22](https://aeturrell.github.io/python4DS/boolean-data.html)
:::

---

# Getting started with Lets-Plot

- [Lets-Plot](https://aeturrell.github.io/python4DS/data-visualise.html)

<!-- ## Prove Activity - Explore Pandas and the Data

**1. How many `.unique()` names does the `names` dataframe contain?** <br>
_Work with a partner to find the answer. You might want to look at this [pandas cheat sheet](https://pandas.pydf.org/Pandas_Cheat_Sheet.pdf)._

::: {.callout-tip title="Hint" collapse="true"}
1. Pull the name column out as a series
1. Use the pandas unique function `pd.unique()`
1. Find the size of the series
:::

::: {.callout-caution collapse="true"}
<!-- section_id: "67d297d3-5455-40d3-b79d-30c112bcf95e" -->
## Expand To See An Example Solution
```{.python}
pd.unique(df.name)
```
:::

**2. What is the range of years in the `names` dataframe?** <br>
_Again, work with a partner and use the pandas cheat sheet._

::: {.callout-tip title="Hint" collapse="true"}
1. Pull the year column out as a series
1. Find the max
1. Find the min
:::

::: {.callout-caution collapse="true"}
<!-- section_id: "907f9957-e604-4f24-a727-9e3fe736b2b7" -->
## Expand To See An Example Solution
```{.python}
pd.unique(df.year).min()
pd.unique(df.year).max()
pd.unique(df.year).size
```
:::

**3. How would you `.query()` for the `name` John?** <br>

::: {.callout-tip title="Hint" collapse="true"}
1. `pd.query()` the name when it is equal to `==` John
:::

::: {.callout-caution collapse="true"}
<!-- section_id: "dcf0092d-41a5-42ca-8e8a-41431940f192" -->
## Expand To See An Example Solution
```{.python}
df.query('name == "John"')
pd.unique(df.query('name == "John"'))
```
:::

**4. What is the range of years in the `names df` for the `name` John?** <br>

::: {.callout-tip title="Hint" collapse="true"}
1. Use your combined knowledge to `.query()`
1. and to find the `.max()` and `.min()`
1. and `.size()` for a particular `name`
:::

:::{.callout-caution collapse="true"}
<!-- section_id: "00d4f9b8-d323-4425-9002-fd191cf08068" -->
## Expand To See An Example Solution
```{.python}
pd.unique(df.query('name == "John"').year).min()
pd.unique(df.query('name == "John"').year).max()
pd.unique(df.query('name == "John"').year).size
```
:::

**5. How would you query for multiple names in a `df`?** <br>

::: {.callout-tip title="Hint" collapse="true"}
1. Similar to what you did above for a single name
1. Now one way is to use the `|` OR bar
1. Another way is to use `in` a `[]` List
:::

:::{.callout-caution collapse="true"}
<!-- section_id: "d411c3f5-fc5c-4a78-9fe5-45a3c3efe270" -->
## Expand To See An Example Solution
```{.python}
#note you can not use pd.unique() with multiple names
df.query('name == "John" | name == "Peter"')
df.query('name in ["John","Peter","Bob"]')
```
::: -->