on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          #cache: 'pip'
      - run: pip install jupyter numpy pandas scikit-learn lets-plot palmerpenguins plotly.express seaborn altair altair_viewer tabulate nbformat nbclient kaleido skimpy matplotlib
      #- run: pip install -r requirements.txt
      #- run: pip install jupyter numpy pandas scikit-learn tabulate altair altair_viewer nbformat nbclient plotly.express

      # Comment out the 2 below section if you are not using R
      # - name: Install R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     #r-version: '4.3.2'
      #     use-public-rspm: true

      # - name: Install R Dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: 
      #       any::tidyverse
      #       any::knitr
      #       any::DT

      # From https://github.com/julia-actions/setup-julia
      # - name: Setup Julia
      #   uses: julia-actions/setup-julia@v1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}